export const userPerformancesData = [
  {
    label: 'Étudiants actifs',
    value: 75.8,
    totalValue: '2156',
    additionalInfo: 'sur 2845 inscrits',
    trend: null,
    icon: 'user',
  },
  {
    label: 'Taux de complétion',
    value: 78,
    totalValue: '78%',
    additionalInfo: null,
    trend: '+2.3% ce mois',
    icon: 'chart',
  },
  {
    label: 'Engagement parents',
    value: 68,
    totalValue: '68%',
    additionalInfo: null,
    trend: '+1.5% ce mois',
    icon: 'group',
  },
  {
    label: 'Note moyenne',
    value: 82.5,
    totalValue: '82.5/100',
    additionalInfo: null,
    trend: '+2.2 points',
    icon: 'award',
  },
];

export const subjectsPerformanceData = [
  {
    id: '1',
    matiere: 'Mathématiques',
    noteAvg: 84,
    completionRate: 82,
    engagement: 76,
    trend: { value: 3.2, isPositive: true },
  },
  {
    id: '2',
    matiere: 'Français',
    noteAvg: 78,
    completionRate: 75,
    engagement: 70,
    trend: { value: 1.5, isPositive: true },
  },
  {
    id: '3',
    matiere: 'Sciences',
    noteAvg: 86,
    completionRate: 79,
    engagement: 82,
    trend: { value: 4.8, isPositive: true },
  },
  {
    id: '4',
    matiere: 'Histoire-Géographie',
    noteAvg: 76,
    completionRate: 72,
    engagement: 65,
    trend: { value: 1.2, isPositive: false },
  },
  {
    id: '5',
    matiere: 'Langues étrangères',
    noteAvg: 82,
    completionRate: 77,
    engagement: 74,
    trend: { value: 2.3, isPositive: true },
  },
  {
    id: '6',
    matiere: 'Arts et culture',
    noteAvg: 90,
    completionRate: 85,
    engagement: 88,
    trend: { value: 5.1, isPositive: true },
  },
  {
    id: '7',
    matiere: 'Arts et culture',
    noteAvg: 90,
    completionRate: 85,
    engagement: 88,
    trend: { value: 5.1, isPositive: true },
  },
  {
    id: '8',
    matiere: 'Arts et culture',
    noteAvg: 90,
    completionRate: 85,
    engagement: 88,
    trend: { value: 5.1, isPositive: true },
  },
  {
    id: '9',
    matiere: 'Arts et culture',
    noteAvg: 90,
    completionRate: 85,
    engagement: 88,
    trend: { value: 5.1, isPositive: true },
  },
];

export const subjectPerformanceData = {
  series: [
    { label: 'Mathématiques', value: 1250, score: 84 },
    { label: 'Français', value: 980, score: 79 },
    { label: 'Sciences', value: 850, score: 88 },
    { label: 'Histoire-Géographie', value: 720, score: 76 },
    { label: 'Langues étrangères', value: 650, score: 81 },
    { label: 'Arts et culture', value: 450, score: 90 },
  ],
};
